name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Dart Pub Publish Check (Dry-run)
        run: dart pub publish --dry-run
